// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/registry.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TagResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagResponse) Reset()         { *m = TagResponse{} }
func (m *TagResponse) String() string { return proto.CompactTextString(m) }
func (*TagResponse) ProtoMessage()    {}
func (*TagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4215e5fe8e6d7e5d, []int{0}
}

func (m *TagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagResponse.Unmarshal(m, b)
}
func (m *TagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagResponse.Marshal(b, m, deterministic)
}
func (m *TagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagResponse.Merge(m, src)
}
func (m *TagResponse) XXX_Size() int {
	return xxx_messageInfo_TagResponse.Size(m)
}
func (m *TagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TagResponse proto.InternalMessageInfo

func (m *TagResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BrokerRequest struct {
	Tag                  []string `protobuf:"bytes,1,rep,name=tag,proto3" json:"tag,omitempty"`
	Id                   uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrokerRequest) Reset()         { *m = BrokerRequest{} }
func (m *BrokerRequest) String() string { return proto.CompactTextString(m) }
func (*BrokerRequest) ProtoMessage()    {}
func (*BrokerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4215e5fe8e6d7e5d, []int{1}
}

func (m *BrokerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerRequest.Unmarshal(m, b)
}
func (m *BrokerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerRequest.Marshal(b, m, deterministic)
}
func (m *BrokerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerRequest.Merge(m, src)
}
func (m *BrokerRequest) XXX_Size() int {
	return xxx_messageInfo_BrokerRequest.Size(m)
}
func (m *BrokerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerRequest proto.InternalMessageInfo

func (m *BrokerRequest) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *BrokerRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BrokerResponse struct {
	Brokers              map[uint32]*Broker `protobuf:"bytes,5,rep,name=brokers,proto3" json:"brokers,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Ids                  []uint32           `protobuf:"varint,6,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BrokerResponse) Reset()         { *m = BrokerResponse{} }
func (m *BrokerResponse) String() string { return proto.CompactTextString(m) }
func (*BrokerResponse) ProtoMessage()    {}
func (*BrokerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4215e5fe8e6d7e5d, []int{2}
}

func (m *BrokerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerResponse.Unmarshal(m, b)
}
func (m *BrokerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerResponse.Marshal(b, m, deterministic)
}
func (m *BrokerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerResponse.Merge(m, src)
}
func (m *BrokerResponse) XXX_Size() int {
	return xxx_messageInfo_BrokerResponse.Size(m)
}
func (m *BrokerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerResponse proto.InternalMessageInfo

func (m *BrokerResponse) GetBrokers() map[uint32]*Broker {
	if m != nil {
		return m.Brokers
	}
	return nil
}

func (m *BrokerResponse) GetIds() []uint32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Broker struct {
	// Registry metadata.
	Tags map[string]string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Broker metadata from ZooKeeper.
	Id                          uint32            `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	Listenersecurityprotocolmap map[string]string `protobuf:"bytes,6,rep,name=listenersecurityprotocolmap,proto3" json:"listenersecurityprotocolmap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Endpoints                   []string          `protobuf:"bytes,7,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Rack                        string            `protobuf:"bytes,8,opt,name=rack,proto3" json:"rack,omitempty"`
	Jmxport                     uint32            `protobuf:"varint,9,opt,name=jmxport,proto3" json:"jmxport,omitempty"`
	Host                        string            `protobuf:"bytes,10,opt,name=host,proto3" json:"host,omitempty"`
	Timestamp                   int64             `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Port                        uint32            `protobuf:"varint,12,opt,name=port,proto3" json:"port,omitempty"`
	Version                     uint32            `protobuf:"varint,13,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}          `json:"-"`
	XXX_unrecognized            []byte            `json:"-"`
	XXX_sizecache               int32             `json:"-"`
}

func (m *Broker) Reset()         { *m = Broker{} }
func (m *Broker) String() string { return proto.CompactTextString(m) }
func (*Broker) ProtoMessage()    {}
func (*Broker) Descriptor() ([]byte, []int) {
	return fileDescriptor_4215e5fe8e6d7e5d, []int{3}
}

func (m *Broker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Broker.Unmarshal(m, b)
}
func (m *Broker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Broker.Marshal(b, m, deterministic)
}
func (m *Broker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Broker.Merge(m, src)
}
func (m *Broker) XXX_Size() int {
	return xxx_messageInfo_Broker.Size(m)
}
func (m *Broker) XXX_DiscardUnknown() {
	xxx_messageInfo_Broker.DiscardUnknown(m)
}

var xxx_messageInfo_Broker proto.InternalMessageInfo

func (m *Broker) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Broker) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Broker) GetListenersecurityprotocolmap() map[string]string {
	if m != nil {
		return m.Listenersecurityprotocolmap
	}
	return nil
}

func (m *Broker) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *Broker) GetRack() string {
	if m != nil {
		return m.Rack
	}
	return ""
}

func (m *Broker) GetJmxport() uint32 {
	if m != nil {
		return m.Jmxport
	}
	return 0
}

func (m *Broker) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Broker) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Broker) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Broker) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type TopicRequest struct {
	Tag                  []string `protobuf:"bytes,1,rep,name=tag,proto3" json:"tag,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicRequest) Reset()         { *m = TopicRequest{} }
func (m *TopicRequest) String() string { return proto.CompactTextString(m) }
func (*TopicRequest) ProtoMessage()    {}
func (*TopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4215e5fe8e6d7e5d, []int{4}
}

func (m *TopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicRequest.Unmarshal(m, b)
}
func (m *TopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicRequest.Marshal(b, m, deterministic)
}
func (m *TopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicRequest.Merge(m, src)
}
func (m *TopicRequest) XXX_Size() int {
	return xxx_messageInfo_TopicRequest.Size(m)
}
func (m *TopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopicRequest proto.InternalMessageInfo

func (m *TopicRequest) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *TopicRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateTopicRequest struct {
	Topic                *Topic   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	TargetBrokerTags     []string `protobuf:"bytes,2,rep,name=target_broker_tags,json=targetBrokerTags,proto3" json:"target_broker_tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTopicRequest) Reset()         { *m = CreateTopicRequest{} }
func (m *CreateTopicRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTopicRequest) ProtoMessage()    {}
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4215e5fe8e6d7e5d, []int{5}
}

func (m *CreateTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTopicRequest.Unmarshal(m, b)
}
func (m *CreateTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTopicRequest.Marshal(b, m, deterministic)
}
func (m *CreateTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTopicRequest.Merge(m, src)
}
func (m *CreateTopicRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTopicRequest.Size(m)
}
func (m *CreateTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTopicRequest proto.InternalMessageInfo

func (m *CreateTopicRequest) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *CreateTopicRequest) GetTargetBrokerTags() []string {
	if m != nil {
		return m.TargetBrokerTags
	}
	return nil
}

type TopicResponse struct {
	Topics               map[string]*Topic `protobuf:"bytes,5,rep,name=topics,proto3" json:"topics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Names                []string          `protobuf:"bytes,6,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TopicResponse) Reset()         { *m = TopicResponse{} }
func (m *TopicResponse) String() string { return proto.CompactTextString(m) }
func (*TopicResponse) ProtoMessage()    {}
func (*TopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4215e5fe8e6d7e5d, []int{6}
}

func (m *TopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicResponse.Unmarshal(m, b)
}
func (m *TopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicResponse.Marshal(b, m, deterministic)
}
func (m *TopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicResponse.Merge(m, src)
}
func (m *TopicResponse) XXX_Size() int {
	return xxx_messageInfo_TopicResponse.Size(m)
}
func (m *TopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TopicResponse proto.InternalMessageInfo

func (m *TopicResponse) GetTopics() map[string]*Topic {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *TopicResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type Topic struct {
	// Registry metadata.
	Tags map[string]string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Topic metadata from ZooKeeper.
	Name                 string            `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Partitions           uint32            `protobuf:"varint,6,opt,name=partitions,proto3" json:"partitions,omitempty"`
	Replication          uint32            `protobuf:"varint,7,opt,name=replication,proto3" json:"replication,omitempty"`
	Configs              map[string]string `protobuf:"bytes,8,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_4215e5fe8e6d7e5d, []int{7}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Topic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Topic) GetPartitions() uint32 {
	if m != nil {
		return m.Partitions
	}
	return 0
}

func (m *Topic) GetReplication() uint32 {
	if m != nil {
		return m.Replication
	}
	return 0
}

func (m *Topic) GetConfigs() map[string]string {
	if m != nil {
		return m.Configs
	}
	return nil
}

type OffsetMapping struct {
	UpstreamOffset       uint64   `protobuf:"varint,1,opt,name=upstream_offset,json=upstreamOffset,proto3" json:"upstream_offset,omitempty"`
	LocalOffset          uint64   `protobuf:"varint,2,opt,name=local_offset,json=localOffset,proto3" json:"local_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OffsetMapping) Reset()         { *m = OffsetMapping{} }
func (m *OffsetMapping) String() string { return proto.CompactTextString(m) }
func (*OffsetMapping) ProtoMessage()    {}
func (*OffsetMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_4215e5fe8e6d7e5d, []int{8}
}

func (m *OffsetMapping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OffsetMapping.Unmarshal(m, b)
}
func (m *OffsetMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OffsetMapping.Marshal(b, m, deterministic)
}
func (m *OffsetMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OffsetMapping.Merge(m, src)
}
func (m *OffsetMapping) XXX_Size() int {
	return xxx_messageInfo_OffsetMapping.Size(m)
}
func (m *OffsetMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_OffsetMapping.DiscardUnknown(m)
}

var xxx_messageInfo_OffsetMapping proto.InternalMessageInfo

func (m *OffsetMapping) GetUpstreamOffset() uint64 {
	if m != nil {
		return m.UpstreamOffset
	}
	return 0
}

func (m *OffsetMapping) GetLocalOffset() uint64 {
	if m != nil {
		return m.LocalOffset
	}
	return 0
}

type TranslateOffsetRequest struct {
	RemoteClusterAlias   string   `protobuf:"bytes,1,opt,name=remote_cluster_alias,json=remoteClusterAlias,proto3" json:"remote_cluster_alias,omitempty"`
	GroupId              string   `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranslateOffsetRequest) Reset()         { *m = TranslateOffsetRequest{} }
func (m *TranslateOffsetRequest) String() string { return proto.CompactTextString(m) }
func (*TranslateOffsetRequest) ProtoMessage()    {}
func (*TranslateOffsetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4215e5fe8e6d7e5d, []int{9}
}

func (m *TranslateOffsetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateOffsetRequest.Unmarshal(m, b)
}
func (m *TranslateOffsetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateOffsetRequest.Marshal(b, m, deterministic)
}
func (m *TranslateOffsetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateOffsetRequest.Merge(m, src)
}
func (m *TranslateOffsetRequest) XXX_Size() int {
	return xxx_messageInfo_TranslateOffsetRequest.Size(m)
}
func (m *TranslateOffsetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateOffsetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateOffsetRequest proto.InternalMessageInfo

func (m *TranslateOffsetRequest) GetRemoteClusterAlias() string {
	if m != nil {
		return m.RemoteClusterAlias
	}
	return ""
}

func (m *TranslateOffsetRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type TranslateOffsetResponse struct {
	Offsets              map[string]*OffsetMapping `protobuf:"bytes,1,rep,name=offsets,proto3" json:"offsets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *TranslateOffsetResponse) Reset()         { *m = TranslateOffsetResponse{} }
func (m *TranslateOffsetResponse) String() string { return proto.CompactTextString(m) }
func (*TranslateOffsetResponse) ProtoMessage()    {}
func (*TranslateOffsetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4215e5fe8e6d7e5d, []int{10}
}

func (m *TranslateOffsetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateOffsetResponse.Unmarshal(m, b)
}
func (m *TranslateOffsetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateOffsetResponse.Marshal(b, m, deterministic)
}
func (m *TranslateOffsetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateOffsetResponse.Merge(m, src)
}
func (m *TranslateOffsetResponse) XXX_Size() int {
	return xxx_messageInfo_TranslateOffsetResponse.Size(m)
}
func (m *TranslateOffsetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateOffsetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateOffsetResponse proto.InternalMessageInfo

func (m *TranslateOffsetResponse) GetOffsets() map[string]*OffsetMapping {
	if m != nil {
		return m.Offsets
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_4215e5fe8e6d7e5d, []int{11}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TagResponse)(nil), "registry.TagResponse")
	proto.RegisterType((*BrokerRequest)(nil), "registry.BrokerRequest")
	proto.RegisterType((*BrokerResponse)(nil), "registry.BrokerResponse")
	proto.RegisterMapType((map[uint32]*Broker)(nil), "registry.BrokerResponse.BrokersEntry")
	proto.RegisterType((*Broker)(nil), "registry.Broker")
	proto.RegisterMapType((map[string]string)(nil), "registry.Broker.ListenersecurityprotocolmapEntry")
	proto.RegisterMapType((map[string]string)(nil), "registry.Broker.TagsEntry")
	proto.RegisterType((*TopicRequest)(nil), "registry.TopicRequest")
	proto.RegisterType((*CreateTopicRequest)(nil), "registry.CreateTopicRequest")
	proto.RegisterType((*TopicResponse)(nil), "registry.TopicResponse")
	proto.RegisterMapType((map[string]*Topic)(nil), "registry.TopicResponse.TopicsEntry")
	proto.RegisterType((*Topic)(nil), "registry.Topic")
	proto.RegisterMapType((map[string]string)(nil), "registry.Topic.ConfigsEntry")
	proto.RegisterMapType((map[string]string)(nil), "registry.Topic.TagsEntry")
	proto.RegisterType((*OffsetMapping)(nil), "registry.OffsetMapping")
	proto.RegisterType((*TranslateOffsetRequest)(nil), "registry.TranslateOffsetRequest")
	proto.RegisterType((*TranslateOffsetResponse)(nil), "registry.TranslateOffsetResponse")
	proto.RegisterMapType((map[string]*OffsetMapping)(nil), "registry.TranslateOffsetResponse.OffsetsEntry")
	proto.RegisterType((*Empty)(nil), "registry.Empty")
}

func init() { proto.RegisterFile("protos/registry.proto", fileDescriptor_4215e5fe8e6d7e5d) }

var fileDescriptor_4215e5fe8e6d7e5d = []byte{
	// 1170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xef, 0x6e, 0x1b, 0x45,
	0x10, 0x97, 0xed, 0x38, 0xb6, 0xe7, 0xec, 0xc6, 0x5d, 0xda, 0xf8, 0x7a, 0x0d, 0x95, 0x7b, 0xa8,
	0xd4, 0x8a, 0x1a, 0x1f, 0x31, 0x88, 0x42, 0xf8, 0x50, 0xd1, 0xa4, 0x2a, 0xa0, 0xf2, 0x47, 0x87,
	0x85, 0x20, 0x08, 0x99, 0x8d, 0xbd, 0xb9, 0x2e, 0xb6, 0xef, 0x8e, 0xdb, 0x75, 0x44, 0x14, 0x45,
	0x42, 0xbc, 0x02, 0x5f, 0x78, 0x0a, 0x24, 0xbe, 0xc1, 0x73, 0xf0, 0x0a, 0x3c, 0x01, 0x4f, 0x80,
	0x76, 0x76, 0x2f, 0x3e, 0xdb, 0xb9, 0x56, 0x0d, 0x9f, 0xb2, 0x33, 0x3b, 0xf3, 0x9b, 0xd9, 0xf9,
	0xf3, 0x3b, 0x07, 0x6e, 0xc6, 0x49, 0x24, 0x23, 0xe1, 0x25, 0x2c, 0xe0, 0x42, 0x26, 0xa7, 0x5d,
	0x94, 0x49, 0x35, 0x95, 0x9d, 0xad, 0x20, 0x8a, 0x82, 0x09, 0xf3, 0x68, 0xcc, 0x3d, 0x1a, 0x86,
	0x91, 0xa4, 0x92, 0x47, 0xa1, 0xd0, 0x76, 0xee, 0x7d, 0xb0, 0xfa, 0x34, 0xf0, 0x99, 0x88, 0xa3,
	0x50, 0x30, 0x62, 0x43, 0x65, 0xca, 0x84, 0xa0, 0x01, 0xb3, 0x0b, 0xed, 0x42, 0xa7, 0xe6, 0xa7,
	0xa2, 0xbb, 0x0b, 0x8d, 0xc7, 0x49, 0x34, 0x66, 0x89, 0xcf, 0x7e, 0x9c, 0x31, 0x21, 0x49, 0x13,
	0x4a, 0x92, 0x06, 0x76, 0xa1, 0x5d, 0xea, 0xd4, 0x7c, 0x75, 0x24, 0xd7, 0xa0, 0xc8, 0x47, 0x76,
	0xb1, 0x5d, 0xe8, 0x34, 0xfc, 0x22, 0x1f, 0xb9, 0x7f, 0x14, 0xe0, 0x5a, 0xea, 0x63, 0xf0, 0x1f,
	0x41, 0xe5, 0x08, 0x35, 0xc2, 0x2e, 0xb7, 0x4b, 0x1d, 0xab, 0x77, 0xaf, 0x7b, 0x91, 0xf8, 0xa2,
	0xa9, 0x11, 0xc5, 0x93, 0x50, 0x26, 0xa7, 0x7e, 0xea, 0xa5, 0xa2, 0xf2, 0x91, 0xb0, 0xd7, 0xdb,
	0xa5, 0x4e, 0xc3, 0x57, 0x47, 0xe7, 0x19, 0xd4, 0xb3, 0xa6, 0xca, 0x62, 0xcc, 0x4e, 0x31, 0xfd,
	0x86, 0xaf, 0x8e, 0xe4, 0x4d, 0x28, 0x9f, 0xd0, 0xc9, 0x8c, 0x61, 0x6a, 0x56, 0xaf, 0xb9, 0x12,
	0x52, 0x5f, 0xef, 0x15, 0xdf, 0x2b, 0xb8, 0xff, 0x96, 0x60, 0x5d, 0x6b, 0x49, 0x17, 0xd6, 0x24,
	0x0d, 0x04, 0xbe, 0xd0, 0xea, 0x39, 0xcb, 0x5e, 0xdd, 0x3e, 0x0d, 0x4c, 0x76, 0x68, 0x67, 0x9e,
	0x5f, 0x4e, 0x9f, 0x4f, 0x04, 0xdc, 0x9e, 0x70, 0x21, 0x59, 0xc8, 0x12, 0xc1, 0x86, 0xb3, 0x84,
	0xcb, 0x53, 0xac, 0xf9, 0x30, 0x9a, 0x4c, 0x69, 0x8c, 0x4f, 0xb0, 0x7a, 0xbb, 0x2b, 0xb0, 0xcf,
	0xf2, 0x7d, 0x74, 0xb4, 0x17, 0xa1, 0x92, 0x2d, 0xa8, 0xb1, 0x70, 0x14, 0x47, 0x3c, 0x94, 0xc2,
	0xae, 0x60, 0x6f, 0xe6, 0x0a, 0x42, 0x60, 0x2d, 0xa1, 0xc3, 0xb1, 0x5d, 0xc5, 0xde, 0xe2, 0x59,
	0xb5, 0xfc, 0x87, 0xe9, 0x4f, 0x71, 0x94, 0x48, 0xbb, 0x86, 0xb9, 0xa7, 0xa2, 0xb2, 0x7e, 0x1e,
	0x09, 0x69, 0x83, 0xb6, 0x56, 0x67, 0x85, 0x2f, 0xf9, 0x94, 0x09, 0x49, 0xa7, 0xb1, 0x6d, 0xb5,
	0x0b, 0x9d, 0x92, 0x3f, 0x57, 0x28, 0x0f, 0x04, 0xaa, 0x23, 0x10, 0x9e, 0x15, 0xfe, 0x09, 0x4b,
	0x04, 0x8f, 0x42, 0xbb, 0xa1, 0xf1, 0x8d, 0xe8, 0x3c, 0x84, 0xda, 0x45, 0x0d, 0xb3, 0x6d, 0xab,
	0xe9, 0xb6, 0xdd, 0xc8, 0xb6, 0xad, 0x96, 0x69, 0x92, 0xf3, 0x19, 0xb4, 0x5f, 0x56, 0xa5, 0x57,
	0xc1, 0x73, 0xdf, 0x81, 0x7a, 0x3f, 0x8a, 0xf9, 0x30, 0x7f, 0xb4, 0x09, 0xac, 0x85, 0x74, 0x9a,
	0xba, 0xe2, 0xd9, 0xe5, 0x40, 0xf6, 0x13, 0x46, 0x25, 0x5b, 0xf0, 0xbd, 0x07, 0x65, 0xa9, 0x64,
	0x8c, 0x6c, 0xf5, 0x36, 0xe6, 0xfd, 0xd5, 0x66, 0xfa, 0x96, 0x3c, 0x00, 0x22, 0x69, 0x12, 0x30,
	0x39, 0xd0, 0x93, 0x3d, 0xc0, 0x51, 0x2b, 0x62, 0xc4, 0xa6, 0xbe, 0xd1, 0xf3, 0xa0, 0x2a, 0xe4,
	0xfe, 0x5e, 0x80, 0x86, 0x89, 0x62, 0x16, 0xe9, 0x03, 0x58, 0x47, 0xa0, 0x74, 0x8f, 0xde, 0x58,
	0x8e, 0x93, 0xae, 0x11, 0x4a, 0x66, 0x4e, 0x8d, 0x8b, 0xaa, 0x84, 0x7a, 0x81, 0x5e, 0xa3, 0x9a,
	0xaf, 0x05, 0xe7, 0x13, 0xb0, 0x32, 0xc6, 0x97, 0x14, 0xf0, 0xde, 0xe2, 0x1e, 0xad, 0x3e, 0x6d,
	0x5e, 0xd1, 0xbf, 0x8a, 0x50, 0x46, 0x25, 0xd9, 0x59, 0xd8, 0xa2, 0x5b, 0x4b, 0x3e, 0x2b, 0x4b,
	0x94, 0x16, 0xba, 0x3c, 0x2f, 0x34, 0xb9, 0x03, 0x10, 0xd3, 0x44, 0x72, 0xe4, 0x2d, 0x7b, 0x1d,
	0x87, 0x28, 0xa3, 0x21, 0x6d, 0xb0, 0x12, 0x16, 0x4f, 0xf8, 0x10, 0x99, 0xcd, 0xae, 0xa0, 0x41,
	0x56, 0x45, 0xde, 0x85, 0xca, 0x30, 0x0a, 0x8f, 0x79, 0x20, 0xec, 0x2a, 0xe6, 0xb1, 0xb5, 0x9c,
	0xc7, 0xbe, 0xbe, 0x36, 0x6c, 0x63, 0x8c, 0xaf, 0x3e, 0xa1, 0x7b, 0x50, 0xcf, 0x22, 0xbe, 0xd2,
	0x34, 0x7e, 0x0b, 0x8d, 0xcf, 0x8f, 0x8f, 0x05, 0x93, 0x9f, 0xd2, 0x38, 0xe6, 0x61, 0x40, 0xee,
	0xc3, 0xc6, 0x2c, 0x16, 0x32, 0x61, 0x74, 0x3a, 0x88, 0xf0, 0x06, 0x81, 0xd6, 0xfc, 0x6b, 0xa9,
	0x5a, 0xdb, 0x93, 0xbb, 0x50, 0x9f, 0x44, 0x43, 0x3a, 0x49, 0xad, 0x8a, 0x68, 0x65, 0xa1, 0x4e,
	0x9b, 0xb8, 0x0c, 0x36, 0xfb, 0x09, 0x0d, 0xc5, 0x84, 0x4a, 0xa6, 0x55, 0xe9, 0xe0, 0xbe, 0x05,
	0x37, 0x12, 0x36, 0x8d, 0x24, 0x1b, 0x0c, 0x27, 0x33, 0x21, 0x59, 0x32, 0xa0, 0x13, 0x4e, 0x85,
	0xc9, 0x99, 0xe8, 0xbb, 0x7d, 0x7d, 0xf5, 0xa1, 0xba, 0x21, 0xb7, 0xa0, 0x1a, 0x24, 0xd1, 0x2c,
	0x1e, 0x18, 0xd6, 0xaf, 0xf9, 0x15, 0x94, 0x3f, 0x1e, 0xb9, 0x7f, 0x16, 0xa0, 0xb5, 0x12, 0xc7,
	0x8c, 0xee, 0x47, 0x50, 0xd1, 0xf9, 0xa5, 0x43, 0xd1, 0xcd, 0x34, 0xe3, 0x72, 0x9f, 0xae, 0x16,
	0xd3, 0xf6, 0x18, 0x77, 0xe7, 0x4b, 0xa8, 0x67, 0x2f, 0x2e, 0xa9, 0xf2, 0xce, 0xe2, 0xc8, 0xb6,
	0xe6, 0x91, 0x16, 0x4a, 0x9c, 0x2d, 0x7f, 0x05, 0xca, 0x4f, 0xa6, 0xb1, 0x3c, 0xed, 0xfd, 0x0c,
	0x50, 0xf5, 0x8d, 0x39, 0xe9, 0x03, 0x3c, 0x4d, 0x57, 0x52, 0x90, 0xd6, 0xea, 0x57, 0x0b, 0x8b,
	0xe8, 0xd8, 0x79, 0x9f, 0x33, 0xf7, 0xb5, 0x5f, 0xfe, 0xfe, 0xe7, 0xd7, 0x62, 0x83, 0x58, 0xde,
	0xc9, 0xae, 0x97, 0x7e, 0xcd, 0x0e, 0xc1, 0x52, 0x44, 0xf6, 0x3f, 0x60, 0x6d, 0x84, 0x25, 0xa4,
	0x99, 0x81, 0xf5, 0xd4, 0x07, 0x82, 0x7c, 0x01, 0xb5, 0xa7, 0x4c, 0xea, 0x8d, 0x26, 0x9b, 0x2b,
	0xf4, 0xa0, 0x81, 0x5b, 0x39, 0xb4, 0xe1, 0x12, 0xc4, 0xad, 0x13, 0x50, 0xb8, 0x86, 0x36, 0xbe,
	0x02, 0x50, 0xd9, 0x5e, 0x15, 0xb2, 0x85, 0x90, 0xd7, 0xc9, 0xc6, 0x1c, 0x52, 0x67, 0x7a, 0x08,
	0x56, 0x86, 0x48, 0x49, 0x66, 0x37, 0x57, 0xf9, 0xd5, 0xc9, 0xb0, 0x0e, 0xb6, 0xc9, 0xdd, 0x42,
	0xd8, 0x4d, 0xf7, 0x7a, 0x06, 0x76, 0x88, 0x7e, 0x7b, 0x85, 0x6d, 0xf2, 0x1d, 0x5c, 0xf7, 0x19,
	0x15, 0x82, 0x07, 0x21, 0x0f, 0x03, 0x93, 0xfa, 0x32, 0x46, 0x7e, 0xce, 0x77, 0x10, 0xdc, 0x26,
	0x9b, 0x19, 0xf0, 0x64, 0x8e, 0x47, 0x46, 0x86, 0x97, 0xcd, 0x1c, 0xe5, 0x57, 0x25, 0xbf, 0x83,
	0x77, 0x31, 0xc4, 0x6d, 0x72, 0x4b, 0x85, 0x98, 0x1a, 0x1c, 0x1d, 0xcb, 0x3b, 0x53, 0xfc, 0x77,
	0x4e, 0x46, 0xe9, 0xef, 0xa8, 0x8b, 0x30, 0xb9, 0x93, 0x92, 0xfb, 0x92, 0x36, 0x86, 0x71, 0x88,
	0xbd, 0x10, 0x46, 0x4f, 0x8c, 0x77, 0xc6, 0x47, 0xe7, 0xe4, 0x6b, 0xa8, 0xf6, 0xa9, 0x2e, 0x51,
	0xee, 0x33, 0x6e, 0x66, 0xf4, 0xf3, 0x9f, 0x8d, 0xee, 0xeb, 0x08, 0xde, 0x72, 0x6e, 0x66, 0xca,
	0x24, 0x69, 0x90, 0xe6, 0x3f, 0x80, 0x8d, 0x03, 0x36, 0x61, 0xa6, 0x93, 0x8a, 0x51, 0xaf, 0x18,
	0x60, 0x3b, 0x27, 0xc0, 0x37, 0xc8, 0xd3, 0xe6, 0x77, 0x5b, 0x6e, 0x6d, 0x72, 0xb0, 0xcd, 0x00,
	0x39, 0x37, 0xb2, 0x2b, 0x84, 0xe0, 0xaa, 0x2a, 0xdf, 0x43, 0x53, 0xe7, 0x3e, 0xff, 0x1c, 0x5f,
	0x35, 0xc2, 0xf6, 0xe5, 0x11, 0x7e, 0x2b, 0x40, 0x73, 0x89, 0xf7, 0x04, 0x69, 0xbf, 0x80, 0x13,
	0x75, 0xac, 0xbb, 0x2f, 0x65, 0x4d, 0xf7, 0x11, 0xc6, 0x7d, 0x9f, 0x3c, 0xc4, 0xaa, 0xa5, 0x46,
	0x3b, 0x86, 0x3e, 0xbd, 0xb3, 0xcb, 0xf8, 0xfe, 0xdc, 0x3b, 0x4b, 0x49, 0xfd, 0xfc, 0x71, 0xf7,
	0xf0, 0x41, 0xc0, 0xe5, 0xf3, 0xd9, 0x51, 0x77, 0x18, 0x4d, 0xbd, 0x03, 0x2a, 0xe9, 0x41, 0x14,
	0x78, 0x63, 0x7a, 0x3c, 0xa6, 0x3b, 0x63, 0x2e, 0x2f, 0xfe, 0xe9, 0xf0, 0xf4, 0x3f, 0x21, 0x47,
	0xeb, 0xf8, 0xf7, 0xed, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x45, 0xe5, 0x2e, 0xe6, 0x95, 0x0c,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryClient interface {
	// GetBrokers returns a BrokerResponse with the brokers field populated
	// with full broker metadata. If the input BrokerRequest.id field is
	// non-nil, a single broker is returned matching the ID specified in the
	// Broker object. Otherwise all brokers are returned, optionally filtered
	// by any provided BrokerRequest.tags parameters.
	GetBrokers(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*BrokerResponse, error)
	// ListBrokers returns a BrokerResponse with the ids field populated
	// with broker IDs. If the input BrokerRequest.id field is non-nil,
	// a single broker ID is returned matching the ID specified in the
	// Broker object if the broker exists. Otherwise all brokers are returned,
	// optionally filtered by any provided BrokerRequest.tags parameters.
	ListBrokers(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*BrokerResponse, error)
	// GetTopics returns a TopicResponse with the topics field populated
	// with full topic metadata. If the input TopicRequest.name field is
	// non-nil, a single topic is returned matching the name specified in the
	// Topic object. Otherwise all topics are returned, optionally filtered
	// by any provided TopicRequest.tags parameters.
	GetTopics(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (*TopicResponse, error)
	// ListTopics returns a TopicResponse with the names field populated
	// with topic names. If the input TopicRequest.name field is non-nil,
	// a single topic name is returned matching the name specified in the
	// Topic object if the topic exists. Otherwise all topics are returned,
	// optionally filtered by any provided TopicRequest.tags parameters.
	ListTopics(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (*TopicResponse, error)
	//
	//CreateTopic creates a topic.
	//Example:
	//$ curl -XPOST "localhost:8080/v1/topics/create" -d '{
	//"topic": {
	//"name": "mytopic",
	//"partitions": 32,
	//"replication": 2,
	//"tags": {"env":"staging"}
	//},
	//"target_broker_tags": ["pool:tests"]
	//}'
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*Empty, error)
	// ReassigningTopics returns a TopicResponse with the names field populated
	// with topic names of all topics undergoing a reassignment.
	ReassigningTopics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TopicResponse, error)
	// TopicMappings returns a BrokerResponse with the ids field
	// populated with broker IDs that hold at least one partition
	// for the requested topic. The topic is specified in the
	// TopicRequest.name field.
	TopicMappings(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (*BrokerResponse, error)
	// BrokerMappings returns a TopicResponse with the names field
	// populated with topics that the broker holds at least one partition
	// for the requested broker. The broker is specified in the
	// BrokerRequest.id field.
	BrokerMappings(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*TopicResponse, error)
	// TagTopic takes a TopicRequest and sets any specified
	// tags for the named topic. Any existing tags that are
	// not specified in the request are left unmodified.
	TagTopic(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (*TagResponse, error)
	// DeleteTopicTags takes a TopicRequest and deletes any
	// specified tags for the named topic. Tags must be provided
	// as key names only; "key:value" will not target the tag "key".
	DeleteTopicTags(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (*TagResponse, error)
	// TagBroker takes a BrokerRequest and sets any specified
	// tags for the named broker. Any existing tags that are
	// not specified in the request are left unmodified.
	TagBroker(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*TagResponse, error)
	// DeleteBrokerTags takes a BrokerRequest and deletes any
	// specified tags for the named broker. Tags must be provided
	// as key names only; "key:value" will not target the tag "key".
	DeleteBrokerTags(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*TagResponse, error)
	// TranslateOffsets returns a TranslateOffsetResponse with the
	// the upstream/local offsets for the provided consumer group
	// populated per topic/partition.
	// The remote cluster alias and consumer group id are specified
	// in the TranslateOffsetRequest.remote_cluster_alias and
	// TranslateOffsetRequest.group_id respectively.
	TranslateOffsets(ctx context.Context, in *TranslateOffsetRequest, opts ...grpc.CallOption) (*TranslateOffsetResponse, error)
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) GetBrokers(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*BrokerResponse, error) {
	out := new(BrokerResponse)
	err := c.cc.Invoke(ctx, "/registry.Registry/GetBrokers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ListBrokers(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*BrokerResponse, error) {
	out := new(BrokerResponse)
	err := c.cc.Invoke(ctx, "/registry.Registry/ListBrokers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetTopics(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (*TopicResponse, error) {
	out := new(TopicResponse)
	err := c.cc.Invoke(ctx, "/registry.Registry/GetTopics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ListTopics(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (*TopicResponse, error) {
	out := new(TopicResponse)
	err := c.cc.Invoke(ctx, "/registry.Registry/ListTopics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/registry.Registry/CreateTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ReassigningTopics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TopicResponse, error) {
	out := new(TopicResponse)
	err := c.cc.Invoke(ctx, "/registry.Registry/ReassigningTopics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) TopicMappings(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (*BrokerResponse, error) {
	out := new(BrokerResponse)
	err := c.cc.Invoke(ctx, "/registry.Registry/TopicMappings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) BrokerMappings(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*TopicResponse, error) {
	out := new(TopicResponse)
	err := c.cc.Invoke(ctx, "/registry.Registry/BrokerMappings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) TagTopic(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (*TagResponse, error) {
	out := new(TagResponse)
	err := c.cc.Invoke(ctx, "/registry.Registry/TagTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) DeleteTopicTags(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (*TagResponse, error) {
	out := new(TagResponse)
	err := c.cc.Invoke(ctx, "/registry.Registry/DeleteTopicTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) TagBroker(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*TagResponse, error) {
	out := new(TagResponse)
	err := c.cc.Invoke(ctx, "/registry.Registry/TagBroker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) DeleteBrokerTags(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*TagResponse, error) {
	out := new(TagResponse)
	err := c.cc.Invoke(ctx, "/registry.Registry/DeleteBrokerTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) TranslateOffsets(ctx context.Context, in *TranslateOffsetRequest, opts ...grpc.CallOption) (*TranslateOffsetResponse, error) {
	out := new(TranslateOffsetResponse)
	err := c.cc.Invoke(ctx, "/registry.Registry/TranslateOffsets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServer is the server API for Registry service.
type RegistryServer interface {
	// GetBrokers returns a BrokerResponse with the brokers field populated
	// with full broker metadata. If the input BrokerRequest.id field is
	// non-nil, a single broker is returned matching the ID specified in the
	// Broker object. Otherwise all brokers are returned, optionally filtered
	// by any provided BrokerRequest.tags parameters.
	GetBrokers(context.Context, *BrokerRequest) (*BrokerResponse, error)
	// ListBrokers returns a BrokerResponse with the ids field populated
	// with broker IDs. If the input BrokerRequest.id field is non-nil,
	// a single broker ID is returned matching the ID specified in the
	// Broker object if the broker exists. Otherwise all brokers are returned,
	// optionally filtered by any provided BrokerRequest.tags parameters.
	ListBrokers(context.Context, *BrokerRequest) (*BrokerResponse, error)
	// GetTopics returns a TopicResponse with the topics field populated
	// with full topic metadata. If the input TopicRequest.name field is
	// non-nil, a single topic is returned matching the name specified in the
	// Topic object. Otherwise all topics are returned, optionally filtered
	// by any provided TopicRequest.tags parameters.
	GetTopics(context.Context, *TopicRequest) (*TopicResponse, error)
	// ListTopics returns a TopicResponse with the names field populated
	// with topic names. If the input TopicRequest.name field is non-nil,
	// a single topic name is returned matching the name specified in the
	// Topic object if the topic exists. Otherwise all topics are returned,
	// optionally filtered by any provided TopicRequest.tags parameters.
	ListTopics(context.Context, *TopicRequest) (*TopicResponse, error)
	//
	//CreateTopic creates a topic.
	//Example:
	//$ curl -XPOST "localhost:8080/v1/topics/create" -d '{
	//"topic": {
	//"name": "mytopic",
	//"partitions": 32,
	//"replication": 2,
	//"tags": {"env":"staging"}
	//},
	//"target_broker_tags": ["pool:tests"]
	//}'
	CreateTopic(context.Context, *CreateTopicRequest) (*Empty, error)
	// ReassigningTopics returns a TopicResponse with the names field populated
	// with topic names of all topics undergoing a reassignment.
	ReassigningTopics(context.Context, *Empty) (*TopicResponse, error)
	// TopicMappings returns a BrokerResponse with the ids field
	// populated with broker IDs that hold at least one partition
	// for the requested topic. The topic is specified in the
	// TopicRequest.name field.
	TopicMappings(context.Context, *TopicRequest) (*BrokerResponse, error)
	// BrokerMappings returns a TopicResponse with the names field
	// populated with topics that the broker holds at least one partition
	// for the requested broker. The broker is specified in the
	// BrokerRequest.id field.
	BrokerMappings(context.Context, *BrokerRequest) (*TopicResponse, error)
	// TagTopic takes a TopicRequest and sets any specified
	// tags for the named topic. Any existing tags that are
	// not specified in the request are left unmodified.
	TagTopic(context.Context, *TopicRequest) (*TagResponse, error)
	// DeleteTopicTags takes a TopicRequest and deletes any
	// specified tags for the named topic. Tags must be provided
	// as key names only; "key:value" will not target the tag "key".
	DeleteTopicTags(context.Context, *TopicRequest) (*TagResponse, error)
	// TagBroker takes a BrokerRequest and sets any specified
	// tags for the named broker. Any existing tags that are
	// not specified in the request are left unmodified.
	TagBroker(context.Context, *BrokerRequest) (*TagResponse, error)
	// DeleteBrokerTags takes a BrokerRequest and deletes any
	// specified tags for the named broker. Tags must be provided
	// as key names only; "key:value" will not target the tag "key".
	DeleteBrokerTags(context.Context, *BrokerRequest) (*TagResponse, error)
	// TranslateOffsets returns a TranslateOffsetResponse with the
	// the upstream/local offsets for the provided consumer group
	// populated per topic/partition.
	// The remote cluster alias and consumer group id are specified
	// in the TranslateOffsetRequest.remote_cluster_alias and
	// TranslateOffsetRequest.group_id respectively.
	TranslateOffsets(context.Context, *TranslateOffsetRequest) (*TranslateOffsetResponse, error)
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_GetBrokers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetBrokers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/GetBrokers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetBrokers(ctx, req.(*BrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ListBrokers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ListBrokers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/ListBrokers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ListBrokers(ctx, req.(*BrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/GetTopics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetTopics(ctx, req.(*TopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/ListTopics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ListTopics(ctx, req.(*TopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/CreateTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ReassigningTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ReassigningTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/ReassigningTopics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ReassigningTopics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_TopicMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).TopicMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/TopicMappings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).TopicMappings(ctx, req.(*TopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_BrokerMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).BrokerMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/BrokerMappings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).BrokerMappings(ctx, req.(*BrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_TagTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).TagTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/TagTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).TagTopic(ctx, req.(*TopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_DeleteTopicTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).DeleteTopicTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/DeleteTopicTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).DeleteTopicTags(ctx, req.(*TopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_TagBroker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).TagBroker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/TagBroker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).TagBroker(ctx, req.(*BrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_DeleteBrokerTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).DeleteBrokerTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/DeleteBrokerTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).DeleteBrokerTags(ctx, req.(*BrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_TranslateOffsets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateOffsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).TranslateOffsets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/TranslateOffsets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).TranslateOffsets(ctx, req.(*TranslateOffsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "registry.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBrokers",
			Handler:    _Registry_GetBrokers_Handler,
		},
		{
			MethodName: "ListBrokers",
			Handler:    _Registry_ListBrokers_Handler,
		},
		{
			MethodName: "GetTopics",
			Handler:    _Registry_GetTopics_Handler,
		},
		{
			MethodName: "ListTopics",
			Handler:    _Registry_ListTopics_Handler,
		},
		{
			MethodName: "CreateTopic",
			Handler:    _Registry_CreateTopic_Handler,
		},
		{
			MethodName: "ReassigningTopics",
			Handler:    _Registry_ReassigningTopics_Handler,
		},
		{
			MethodName: "TopicMappings",
			Handler:    _Registry_TopicMappings_Handler,
		},
		{
			MethodName: "BrokerMappings",
			Handler:    _Registry_BrokerMappings_Handler,
		},
		{
			MethodName: "TagTopic",
			Handler:    _Registry_TagTopic_Handler,
		},
		{
			MethodName: "DeleteTopicTags",
			Handler:    _Registry_DeleteTopicTags_Handler,
		},
		{
			MethodName: "TagBroker",
			Handler:    _Registry_TagBroker_Handler,
		},
		{
			MethodName: "DeleteBrokerTags",
			Handler:    _Registry_DeleteBrokerTags_Handler,
		},
		{
			MethodName: "TranslateOffsets",
			Handler:    _Registry_TranslateOffsets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/registry.proto",
}
